// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {domain} from '../models';
import {ai} from '../models';
import {context} from '../models';
import {scanner} from '../models';
import {llamacpp} from '../models';

export function AddAssetsToGenerationGroup(arg1:number,arg2:Array<number>):Promise<void>;

export function AddAssetsToWork(arg1:number,arg2:Array<number>):Promise<void>;

export function AddLibrary(arg1:string,arg2:string):Promise<commands.LibraryDTO>;

export function AttachAssetsToPost(arg1:number,arg2:Array<number>):Promise<void>;

export function BuildImagePrompt(arg1:commands.ImagePromptRequestDTO):Promise<commands.ImagePromptResultDTO>;

export function BulkDeleteAssets(arg1:Array<number>):Promise<void>;

export function BulkUpdateColorLabel(arg1:Array<number>,arg2:string):Promise<void>;

export function BulkUpdateFavorite(arg1:Array<number>,arg2:boolean):Promise<void>;

export function BulkUpdateRating(arg1:Array<number>,arg2:number):Promise<void>;

export function BulkUpdateStatus(arg1:Array<number>,arg2:string):Promise<void>;

export function CancelAIJob(arg1:number):Promise<void>;

export function CancelLegacyStorageMigration():Promise<commands.AIStorageInfo>;

export function CancelScan():Promise<void>;

export function CancelSemanticSearch(arg1:string):Promise<void>;

export function CopyAssets(arg1:commands.CopyRequest):Promise<commands.CopyResult>;

export function CreateAssetRelation(arg1:number,arg2:number,arg3:string,arg4:string):Promise<commands.AssetRelationDTO>;

export function CreateGenerationGroup(arg1:commands.CreateGenerationGroupRequest):Promise<commands.GenerationGroupDTO>;

export function CreateModelProfile(arg1:commands.ModelProfileInput):Promise<commands.ModelProfileDTO>;

export function CreatePostAccount(arg1:number,arg2:string,arg3:string):Promise<commands.PostAccountDTO>;

export function CreatePostDraft(arg1:string,arg2:string,arg3:string):Promise<commands.PostDTO>;

export function CreatePostRecord(arg1:commands.PostRecordRequest):Promise<commands.PostRecordDTO>;

export function CreatePostTarget(arg1:string,arg2:string):Promise<commands.PostTargetDTO>;

export function CreatePromptProject(arg1:commands.PromptProjectInput):Promise<commands.PromptProjectDTO>;

export function CreatePromptProjectFromImage(arg1:commands.ImagePromptRequestDTO):Promise<commands.ImagePromptProjectResultDTO>;

export function CreatePromptVariant(arg1:number,arg2:string,arg3:number):Promise<commands.PromptVariantDTO>;

export function CreatePromptVersion(arg1:commands.PromptVersionInput):Promise<commands.PromptVersionDTO>;

export function CreateTag(arg1:string,arg2:string):Promise<commands.TagDTO>;

export function CreateWork(arg1:string,arg2:string,arg3:Array<number>):Promise<commands.WorkDTO>;

export function DeleteAssetFiles(arg1:Array<number>):Promise<commands.DeleteAssetFilesResult>;

export function DeleteAssetRelation(arg1:number):Promise<void>;

export function DeleteModelProfile(arg1:string):Promise<void>;

export function DeletePost(arg1:number):Promise<void>;

export function DeletePostAccount(arg1:number):Promise<void>;

export function DeletePostTarget(arg1:number):Promise<void>;

export function DeletePromptProject(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DisableLibrary(arg1:number):Promise<void>;

export function DuplicateModelProfile(arg1:string,arg2:string):Promise<commands.ModelProfileDTO>;

export function EnableLibrary(arg1:number):Promise<void>;

export function EnqueueAutomaticLightweightVisionAssets(arg1:Array<number>):Promise<number>;

export function EnqueueAutomaticSemanticAssets(arg1:Array<number>):Promise<number>;

export function EnqueueAutomaticTaggerAssets(arg1:Array<number>):Promise<number>;

export function EnqueueLightweightVisionBackfill():Promise<number>;

export function EnqueueSemanticBackfill():Promise<number>;

export function EnsureSemanticSearchReady():Promise<void>;

export function GetAIAnalyses(arg1:number):Promise<Array<domain.AIAnalysis>>;

export function GetAIHealthSnapshot():Promise<commands.AIHealthSnapshot>;

export function GetAIModelCachePath():Promise<string>;

export function GetAIRuntimeStatuses():Promise<Array<ai.RuntimeStatus>>;

export function GetAISettings():Promise<domain.AISettings>;

export function GetAIStorageInfo():Promise<commands.AIStorageInfo>;

export function GetAdvancedVisionRun(arg1:number):Promise<commands.AdvancedVisionRunDTO>;

export function GetAdvancedVisionStatus():Promise<commands.AdvancedVisionStatusInfo>;

export function GetAppBootstrap():Promise<{[key: string]: any}>;

export function GetAssetCreativeContext(arg1:number):Promise<commands.AssetCreativeContextDTO>;

export function GetAssetDetail(arg1:number):Promise<commands.AssetDTO>;

export function GetAssetGenerationMetadata(arg1:number,arg2:boolean):Promise<commands.AssetGenerationMetadataDTO>;

export function GetDefaultLightweightVisionModelInfo():Promise<commands.LightweightVisionModelInfo>;

export function GetDefaultSemanticModelInfo():Promise<commands.SemanticModelInfo>;

export function GetExcludedDirs(arg1:number):Promise<Array<string>>;

export function GetFolderTree(arg1:number):Promise<Array<commands.FolderDTO>>;

export function GetLightweightVisionAnalysis(arg1:number):Promise<commands.LightweightVisionAnalysisDTO>;

export function GetModelProfile(arg1:string):Promise<commands.ModelProfileDTO>;

export function GetPostRecordsByAsset(arg1:number):Promise<Array<commands.PostRecordDTO>>;

export function GetPostsByAsset(arg1:number):Promise<Array<commands.PostDTO>>;

export function GetPromptEngineStatus():Promise<commands.PromptEngineStatusInfo>;

export function GetPromptProject(arg1:number,arg2:boolean):Promise<commands.PromptProjectDTO>;

export function GetSemanticIndexStatus():Promise<commands.SemanticIndexStatus>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSupportedExtensions():Promise<Array<string>>;

export function GetTaggerReviewJSON(arg1:number):Promise<string>;

export function GetViewerAssetDetail(arg1:number):Promise<commands.AssetDTO>;

export function HandleScannedAssetChanges(arg1:Array<number>):Promise<number>;

export function InstallAdvancedVisionModel(arg1:string):Promise<ai.InstalledModelInfo>;

export function InstallAdvancedVisionRuntime():Promise<commands.LightweightRuntimeInfo>;

export function InstallDefaultLightweightVisionModel():Promise<ai.InstalledModelInfo>;

export function InstallDefaultSemanticModel():Promise<ai.InstalledModelInfo>;

export function InstallLightweightVisionRuntime():Promise<commands.LightweightRuntimeInfo>;

export function InstallPromptEngineModel(arg1:string):Promise<ai.InstalledModelInfo>;

export function InstallPromptEngineRuntime():Promise<commands.LightweightRuntimeInfo>;

export function IsAICapabilityEnabled(arg1:string):Promise<boolean>;

export function IsShuttingDown():Promise<boolean>;

export function LightweightVisionAnalysisHandler(arg1:context.Context,arg2:domain.AIJob):Promise<ai.AnalysisOutput>;

export function ListAIJobs(arg1:number):Promise<Array<domain.AIJob>>;

export function ListAdvancedVisionRunsForAsset(arg1:number,arg2:number):Promise<Array<commands.AdvancedVisionRunDTO>>;

export function ListAssets(arg1:commands.AssetListRequest):Promise<commands.AssetListResponse>;

export function ListGenerationGroups(arg1:number):Promise<Array<commands.GenerationGroupDTO>>;

export function ListInstalledAIModels():Promise<Array<ai.InstalledModelInfo>>;

export function ListLibraries():Promise<Array<commands.LibraryDTO>>;

export function ListModelProfiles():Promise<Array<commands.ModelProfileDTO>>;

export function ListPostAccounts():Promise<Array<commands.PostAccountDTO>>;

export function ListPostRecords(arg1:number,arg2:number):Promise<Array<commands.PostRecordDTO>>;

export function ListPostTargets():Promise<Array<commands.PostTargetDTO>>;

export function ListPosts(arg1:number,arg2:number):Promise<Array<commands.PostDTO>>;

export function ListPromptProjects(arg1:boolean,arg2:number):Promise<Array<commands.PromptProjectDTO>>;

export function ListSimilarAssets(arg1:number,arg2:commands.AssetListRequest):Promise<commands.AssetListResponse>;

export function ListTags():Promise<Array<commands.TagDTO>>;

export function ListWorks(arg1:number):Promise<Array<commands.WorkDTO>>;

export function LoadAdvancedVisionModel(arg1:string):Promise<void>;

export function LoadDefaultLightweightVisionModel():Promise<void>;

export function LoadDefaultSemanticModel():Promise<void>;

export function LoadPromptEngineModel(arg1:string):Promise<void>;

export function MoveAssets(arg1:commands.MoveRequest):Promise<commands.MoveResult>;

export function PatchAISettings(arg1:{[key: string]: boolean}):Promise<domain.AISettings>;

export function ReanalyzeAssets(arg1:Array<number>,arg2:string,arg3:number):Promise<number>;

export function ReanalyzeFolder(arg1:number,arg2:string,arg3:boolean,arg4:string,arg5:number):Promise<number>;

export function ReanalyzeLibrary(arg1:number,arg2:string,arg3:number):Promise<number>;

export function RemoveAIModel(arg1:string,arg2:string):Promise<void>;

export function RemoveAdvancedVisionModel(arg1:string):Promise<void>;

export function RemoveAdvancedVisionRuntime():Promise<void>;

export function RemoveDefaultLightweightVisionModel():Promise<void>;

export function RemoveLibrary(arg1:number):Promise<void>;

export function RemoveLightweightVisionRuntime():Promise<void>;

export function RemovePromptEngineModel(arg1:string):Promise<void>;

export function RemovePromptEngineRuntime():Promise<void>;

export function RequestLegacyStorageMigration():Promise<commands.AIStorageInfo>;

export function RestoreAdvancedVisionModel():Promise<void>;

export function RestoreDefaultLightweightVisionModel():Promise<void>;

export function RestoreDefaultSemanticModel():Promise<void>;

export function RestorePromptEngineModel():Promise<void>;

export function RestorePromptProject(arg1:number):Promise<void>;

export function RetryAIJob(arg1:number):Promise<void>;

export function ReviewTaggerSuggestions(arg1:number,arg2:number,arg3:string):Promise<void>;

export function RunAdvancedVision(arg1:string,arg2:Array<number>,arg3:string):Promise<commands.AdvancedVisionRunDTO>;

export function RunPromptEngine(arg1:commands.PromptEngineRequestDTO):Promise<commands.PromptEngineResultDTO>;

export function ScanFolder(arg1:string,arg2:number,arg3:number):Promise<scanner.FolderScanResult>;

export function ScanLibrary(arg1:number):Promise<void>;

export function ScanLibraryViewer(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function SemanticAnalysisHandler(arg1:context.Context,arg2:domain.AIJob):Promise<ai.AnalysisOutput>;

export function SemanticSearchAssets(arg1:commands.AssetListRequest):Promise<commands.AssetListResponse>;

export function SemanticSearchAssetsWithID(arg1:commands.AssetListRequest,arg2:string):Promise<commands.AssetListResponse>;

export function SemanticSearchPage(arg1:string,arg2:number,arg3:number):Promise<commands.AssetListResponse>;

export function SetAIJobQueue(arg1:ai.JobQueue):Promise<void>;

export function SetAIManager(arg1:ai.Manager):Promise<void>;

export function SetAISettings(arg1:domain.AISettings):Promise<domain.AISettings>;

export function SetAssetTags(arg1:number,arg2:Array<number>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetExcludedDirs(arg1:number,arg2:Array<string>):Promise<void>;

export function SetLlamaRuntimeStore(arg1:llamacpp.RuntimeStore):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetSupportedExtensions(arg1:Array<string>):Promise<void>;

export function ShutdownBackground(arg1:context.Context):Promise<void>;

export function StartAIRestore():Promise<boolean>;

export function SyncLibraryViewer(arg1:number):Promise<scanner.SyncResult>;

export function TaggerAnalysisHandler(arg1:context.Context,arg2:domain.AIJob):Promise<ai.AnalysisOutput>;

export function ToggleAssetFavorite(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAssetColorLabel(arg1:number,arg2:string):Promise<void>;

export function UpdateAssetNote(arg1:number,arg2:string):Promise<void>;

export function UpdateAssetRating(arg1:number,arg2:number):Promise<void>;

export function UpdateAssetStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateLibrary(arg1:number,arg2:string,arg3:string):Promise<commands.LibraryDTO>;

export function UpdateModelProfile(arg1:string,arg2:commands.ModelProfileInput):Promise<commands.ModelProfileDTO>;

export function UpdatePost(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<commands.PostDTO>;

export function UpdatePromptProject(arg1:number,arg2:commands.PromptProjectInput):Promise<commands.PromptProjectDTO>;

export function VerifyAIModel(arg1:string,arg2:string):Promise<ai.InstalledModelInfo>;
