// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAssetsToGenerationGroup(arg1, arg2) {
  return window['go']['commands']['AppCommands']['AddAssetsToGenerationGroup'](arg1, arg2);
}

export function AddAssetsToWork(arg1, arg2) {
  return window['go']['commands']['AppCommands']['AddAssetsToWork'](arg1, arg2);
}

export function AddLibrary(arg1, arg2) {
  return window['go']['commands']['AppCommands']['AddLibrary'](arg1, arg2);
}

export function AttachAssetsToPost(arg1, arg2) {
  return window['go']['commands']['AppCommands']['AttachAssetsToPost'](arg1, arg2);
}

export function BuildImagePrompt(arg1) {
  return window['go']['commands']['AppCommands']['BuildImagePrompt'](arg1);
}

export function BulkDeleteAssets(arg1) {
  return window['go']['commands']['AppCommands']['BulkDeleteAssets'](arg1);
}

export function BulkUpdateColorLabel(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateColorLabel'](arg1, arg2);
}

export function BulkUpdateFavorite(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateFavorite'](arg1, arg2);
}

export function BulkUpdateRating(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateRating'](arg1, arg2);
}

export function BulkUpdateStatus(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateStatus'](arg1, arg2);
}

export function CancelAIJob(arg1) {
  return window['go']['commands']['AppCommands']['CancelAIJob'](arg1);
}

export function CancelLegacyStorageMigration() {
  return window['go']['commands']['AppCommands']['CancelLegacyStorageMigration']();
}

export function CancelScan() {
  return window['go']['commands']['AppCommands']['CancelScan']();
}

export function CancelSemanticSearch(arg1) {
  return window['go']['commands']['AppCommands']['CancelSemanticSearch'](arg1);
}

export function CopyAssets(arg1) {
  return window['go']['commands']['AppCommands']['CopyAssets'](arg1);
}

export function CreateAssetRelation(arg1, arg2, arg3, arg4) {
  return window['go']['commands']['AppCommands']['CreateAssetRelation'](arg1, arg2, arg3, arg4);
}

export function CreateGenerationGroup(arg1) {
  return window['go']['commands']['AppCommands']['CreateGenerationGroup'](arg1);
}

export function CreateModelProfile(arg1) {
  return window['go']['commands']['AppCommands']['CreateModelProfile'](arg1);
}

export function CreatePostAccount(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['CreatePostAccount'](arg1, arg2, arg3);
}

export function CreatePostDraft(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['CreatePostDraft'](arg1, arg2, arg3);
}

export function CreatePostRecord(arg1) {
  return window['go']['commands']['AppCommands']['CreatePostRecord'](arg1);
}

export function CreatePostTarget(arg1, arg2) {
  return window['go']['commands']['AppCommands']['CreatePostTarget'](arg1, arg2);
}

export function CreatePromptProject(arg1) {
  return window['go']['commands']['AppCommands']['CreatePromptProject'](arg1);
}

export function CreatePromptProjectFromImage(arg1) {
  return window['go']['commands']['AppCommands']['CreatePromptProjectFromImage'](arg1);
}

export function CreatePromptVariant(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['CreatePromptVariant'](arg1, arg2, arg3);
}

export function CreatePromptVersion(arg1) {
  return window['go']['commands']['AppCommands']['CreatePromptVersion'](arg1);
}

export function CreateTag(arg1, arg2) {
  return window['go']['commands']['AppCommands']['CreateTag'](arg1, arg2);
}

export function CreateWork(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['CreateWork'](arg1, arg2, arg3);
}

export function DeleteAssetFiles(arg1) {
  return window['go']['commands']['AppCommands']['DeleteAssetFiles'](arg1);
}

export function DeleteAssetRelation(arg1) {
  return window['go']['commands']['AppCommands']['DeleteAssetRelation'](arg1);
}

export function DeleteModelProfile(arg1) {
  return window['go']['commands']['AppCommands']['DeleteModelProfile'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['commands']['AppCommands']['DeletePost'](arg1);
}

export function DeletePostAccount(arg1) {
  return window['go']['commands']['AppCommands']['DeletePostAccount'](arg1);
}

export function DeletePostTarget(arg1) {
  return window['go']['commands']['AppCommands']['DeletePostTarget'](arg1);
}

export function DeletePromptProject(arg1) {
  return window['go']['commands']['AppCommands']['DeletePromptProject'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['commands']['AppCommands']['DeleteTag'](arg1);
}

export function DisableLibrary(arg1) {
  return window['go']['commands']['AppCommands']['DisableLibrary'](arg1);
}

export function DuplicateModelProfile(arg1, arg2) {
  return window['go']['commands']['AppCommands']['DuplicateModelProfile'](arg1, arg2);
}

export function EnableLibrary(arg1) {
  return window['go']['commands']['AppCommands']['EnableLibrary'](arg1);
}

export function EnqueueAutomaticLightweightVisionAssets(arg1) {
  return window['go']['commands']['AppCommands']['EnqueueAutomaticLightweightVisionAssets'](arg1);
}

export function EnqueueAutomaticSemanticAssets(arg1) {
  return window['go']['commands']['AppCommands']['EnqueueAutomaticSemanticAssets'](arg1);
}

export function EnqueueAutomaticTaggerAssets(arg1) {
  return window['go']['commands']['AppCommands']['EnqueueAutomaticTaggerAssets'](arg1);
}

export function EnqueueLightweightVisionBackfill() {
  return window['go']['commands']['AppCommands']['EnqueueLightweightVisionBackfill']();
}

export function EnqueueSemanticBackfill() {
  return window['go']['commands']['AppCommands']['EnqueueSemanticBackfill']();
}

export function EnsureSemanticSearchReady() {
  return window['go']['commands']['AppCommands']['EnsureSemanticSearchReady']();
}

export function GetAIAnalyses(arg1) {
  return window['go']['commands']['AppCommands']['GetAIAnalyses'](arg1);
}

export function GetAIHealthSnapshot() {
  return window['go']['commands']['AppCommands']['GetAIHealthSnapshot']();
}

export function GetAIModelCachePath() {
  return window['go']['commands']['AppCommands']['GetAIModelCachePath']();
}

export function GetAIRuntimeStatuses() {
  return window['go']['commands']['AppCommands']['GetAIRuntimeStatuses']();
}

export function GetAISettings() {
  return window['go']['commands']['AppCommands']['GetAISettings']();
}

export function GetAIStorageInfo() {
  return window['go']['commands']['AppCommands']['GetAIStorageInfo']();
}

export function GetAdvancedVisionRun(arg1) {
  return window['go']['commands']['AppCommands']['GetAdvancedVisionRun'](arg1);
}

export function GetAdvancedVisionStatus() {
  return window['go']['commands']['AppCommands']['GetAdvancedVisionStatus']();
}

export function GetAppBootstrap() {
  return window['go']['commands']['AppCommands']['GetAppBootstrap']();
}

export function GetAssetCreativeContext(arg1) {
  return window['go']['commands']['AppCommands']['GetAssetCreativeContext'](arg1);
}

export function GetAssetDetail(arg1) {
  return window['go']['commands']['AppCommands']['GetAssetDetail'](arg1);
}

export function GetAssetGenerationMetadata(arg1, arg2) {
  return window['go']['commands']['AppCommands']['GetAssetGenerationMetadata'](arg1, arg2);
}

export function GetDefaultLightweightVisionModelInfo() {
  return window['go']['commands']['AppCommands']['GetDefaultLightweightVisionModelInfo']();
}

export function GetDefaultSemanticModelInfo() {
  return window['go']['commands']['AppCommands']['GetDefaultSemanticModelInfo']();
}

export function GetExcludedDirs(arg1) {
  return window['go']['commands']['AppCommands']['GetExcludedDirs'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['commands']['AppCommands']['GetFolderTree'](arg1);
}

export function GetLightweightVisionAnalysis(arg1) {
  return window['go']['commands']['AppCommands']['GetLightweightVisionAnalysis'](arg1);
}

export function GetModelProfile(arg1) {
  return window['go']['commands']['AppCommands']['GetModelProfile'](arg1);
}

export function GetPostRecordsByAsset(arg1) {
  return window['go']['commands']['AppCommands']['GetPostRecordsByAsset'](arg1);
}

export function GetPostsByAsset(arg1) {
  return window['go']['commands']['AppCommands']['GetPostsByAsset'](arg1);
}

export function GetPromptEngineStatus() {
  return window['go']['commands']['AppCommands']['GetPromptEngineStatus']();
}

export function GetPromptProject(arg1, arg2) {
  return window['go']['commands']['AppCommands']['GetPromptProject'](arg1, arg2);
}

export function GetSemanticIndexStatus() {
  return window['go']['commands']['AppCommands']['GetSemanticIndexStatus']();
}

export function GetSemanticPipelineDiagnostics() {
  return window['go']['commands']['AppCommands']['GetSemanticPipelineDiagnostics']();
}

export function GetSetting(arg1) {
  return window['go']['commands']['AppCommands']['GetSetting'](arg1);
}

export function GetSupportedExtensions() {
  return window['go']['commands']['AppCommands']['GetSupportedExtensions']();
}

export function GetTaggerReviewJSON(arg1) {
  return window['go']['commands']['AppCommands']['GetTaggerReviewJSON'](arg1);
}

export function GetTaggerThresholdOverridesJSON() {
  return window['go']['commands']['AppCommands']['GetTaggerThresholdOverridesJSON']();
}

export function GetViewerAssetDetail(arg1) {
  return window['go']['commands']['AppCommands']['GetViewerAssetDetail'](arg1);
}

export function HandleScannedAssetChanges(arg1) {
  return window['go']['commands']['AppCommands']['HandleScannedAssetChanges'](arg1);
}

export function InstallAdvancedVisionModel(arg1) {
  return window['go']['commands']['AppCommands']['InstallAdvancedVisionModel'](arg1);
}

export function InstallAdvancedVisionRuntime() {
  return window['go']['commands']['AppCommands']['InstallAdvancedVisionRuntime']();
}

export function InstallDefaultLightweightVisionModel() {
  return window['go']['commands']['AppCommands']['InstallDefaultLightweightVisionModel']();
}

export function InstallDefaultSemanticModel() {
  return window['go']['commands']['AppCommands']['InstallDefaultSemanticModel']();
}

export function InstallLightweightVisionRuntime() {
  return window['go']['commands']['AppCommands']['InstallLightweightVisionRuntime']();
}

export function InstallPromptEngineModel(arg1) {
  return window['go']['commands']['AppCommands']['InstallPromptEngineModel'](arg1);
}

export function InstallPromptEngineRuntime() {
  return window['go']['commands']['AppCommands']['InstallPromptEngineRuntime']();
}

export function IsAICapabilityEnabled(arg1) {
  return window['go']['commands']['AppCommands']['IsAICapabilityEnabled'](arg1);
}

export function IsShuttingDown() {
  return window['go']['commands']['AppCommands']['IsShuttingDown']();
}

export function LightweightVisionAnalysisHandler(arg1, arg2) {
  return window['go']['commands']['AppCommands']['LightweightVisionAnalysisHandler'](arg1, arg2);
}

export function ListAIJobs(arg1) {
  return window['go']['commands']['AppCommands']['ListAIJobs'](arg1);
}

export function ListAdvancedVisionRunsForAsset(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ListAdvancedVisionRunsForAsset'](arg1, arg2);
}

export function ListAssets(arg1) {
  return window['go']['commands']['AppCommands']['ListAssets'](arg1);
}

export function ListGenerationGroups(arg1) {
  return window['go']['commands']['AppCommands']['ListGenerationGroups'](arg1);
}

export function ListInstalledAIModels() {
  return window['go']['commands']['AppCommands']['ListInstalledAIModels']();
}

export function ListLibraries() {
  return window['go']['commands']['AppCommands']['ListLibraries']();
}

export function ListModelProfiles() {
  return window['go']['commands']['AppCommands']['ListModelProfiles']();
}

export function ListPostAccounts() {
  return window['go']['commands']['AppCommands']['ListPostAccounts']();
}

export function ListPostRecords(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ListPostRecords'](arg1, arg2);
}

export function ListPostTargets() {
  return window['go']['commands']['AppCommands']['ListPostTargets']();
}

export function ListPosts(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ListPosts'](arg1, arg2);
}

export function ListPromptProjects(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ListPromptProjects'](arg1, arg2);
}

export function ListSimilarAssets(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ListSimilarAssets'](arg1, arg2);
}

export function ListTags() {
  return window['go']['commands']['AppCommands']['ListTags']();
}

export function ListWorks(arg1) {
  return window['go']['commands']['AppCommands']['ListWorks'](arg1);
}

export function LoadAdvancedVisionModel(arg1) {
  return window['go']['commands']['AppCommands']['LoadAdvancedVisionModel'](arg1);
}

export function LoadDefaultLightweightVisionModel() {
  return window['go']['commands']['AppCommands']['LoadDefaultLightweightVisionModel']();
}

export function LoadDefaultSemanticModel() {
  return window['go']['commands']['AppCommands']['LoadDefaultSemanticModel']();
}

export function LoadPromptEngineModel(arg1) {
  return window['go']['commands']['AppCommands']['LoadPromptEngineModel'](arg1);
}

export function MoveAssets(arg1) {
  return window['go']['commands']['AppCommands']['MoveAssets'](arg1);
}

export function PatchAISettings(arg1) {
  return window['go']['commands']['AppCommands']['PatchAISettings'](arg1);
}

export function ReanalyzeAssets(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['ReanalyzeAssets'](arg1, arg2, arg3);
}

export function ReanalyzeFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['commands']['AppCommands']['ReanalyzeFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function ReanalyzeLibrary(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['ReanalyzeLibrary'](arg1, arg2, arg3);
}

export function RemoveAIModel(arg1, arg2) {
  return window['go']['commands']['AppCommands']['RemoveAIModel'](arg1, arg2);
}

export function RemoveAdvancedVisionModel(arg1) {
  return window['go']['commands']['AppCommands']['RemoveAdvancedVisionModel'](arg1);
}

export function RemoveAdvancedVisionRuntime() {
  return window['go']['commands']['AppCommands']['RemoveAdvancedVisionRuntime']();
}

export function RemoveDefaultLightweightVisionModel() {
  return window['go']['commands']['AppCommands']['RemoveDefaultLightweightVisionModel']();
}

export function RemoveLibrary(arg1) {
  return window['go']['commands']['AppCommands']['RemoveLibrary'](arg1);
}

export function RemoveLightweightVisionRuntime() {
  return window['go']['commands']['AppCommands']['RemoveLightweightVisionRuntime']();
}

export function RemovePromptEngineModel(arg1) {
  return window['go']['commands']['AppCommands']['RemovePromptEngineModel'](arg1);
}

export function RemovePromptEngineRuntime() {
  return window['go']['commands']['AppCommands']['RemovePromptEngineRuntime']();
}

export function RequestLegacyStorageMigration() {
  return window['go']['commands']['AppCommands']['RequestLegacyStorageMigration']();
}

export function RestoreAdvancedVisionModel() {
  return window['go']['commands']['AppCommands']['RestoreAdvancedVisionModel']();
}

export function RestoreDefaultLightweightVisionModel() {
  return window['go']['commands']['AppCommands']['RestoreDefaultLightweightVisionModel']();
}

export function RestoreDefaultSemanticModel() {
  return window['go']['commands']['AppCommands']['RestoreDefaultSemanticModel']();
}

export function RestorePromptEngineModel() {
  return window['go']['commands']['AppCommands']['RestorePromptEngineModel']();
}

export function RestorePromptProject(arg1) {
  return window['go']['commands']['AppCommands']['RestorePromptProject'](arg1);
}

export function ResetSemanticPipelineDiagnostics() {
  return window['go']['commands']['AppCommands']['ResetSemanticPipelineDiagnostics']();
}

export function RetryAIJob(arg1) {
  return window['go']['commands']['AppCommands']['RetryAIJob'](arg1);
}

export function ReviewTaggerSuggestions(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['ReviewTaggerSuggestions'](arg1, arg2, arg3);
}

export function RunAdvancedVision(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['RunAdvancedVision'](arg1, arg2, arg3);
}

export function RunPromptEngine(arg1) {
  return window['go']['commands']['AppCommands']['RunPromptEngine'](arg1);
}

export function ScanFolder(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['ScanFolder'](arg1, arg2, arg3);
}

export function ScanLibrary(arg1) {
  return window['go']['commands']['AppCommands']['ScanLibrary'](arg1);
}

export function ScanLibraryViewer(arg1) {
  return window['go']['commands']['AppCommands']['ScanLibraryViewer'](arg1);
}

export function SelectFolder() {
  return window['go']['commands']['AppCommands']['SelectFolder']();
}

export function SemanticAnalysisHandler(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SemanticAnalysisHandler'](arg1, arg2);
}

export function SemanticSearchAssets(arg1) {
  return window['go']['commands']['AppCommands']['SemanticSearchAssets'](arg1);
}

export function SemanticSearchAssetsWithID(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SemanticSearchAssetsWithID'](arg1, arg2);
}

export function SemanticSearchPage(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['SemanticSearchPage'](arg1, arg2, arg3);
}

export function SetAIJobQueue(arg1) {
  return window['go']['commands']['AppCommands']['SetAIJobQueue'](arg1);
}

export function SetAIManager(arg1) {
  return window['go']['commands']['AppCommands']['SetAIManager'](arg1);
}

export function SetAISettings(arg1) {
  return window['go']['commands']['AppCommands']['SetAISettings'](arg1);
}

export function SetAssetTags(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SetAssetTags'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['commands']['AppCommands']['SetContext'](arg1);
}

export function SetExcludedDirs(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SetExcludedDirs'](arg1, arg2);
}

export function SetLlamaRuntimeStore(arg1) {
  return window['go']['commands']['AppCommands']['SetLlamaRuntimeStore'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SetSetting'](arg1, arg2);
}

export function SetSupportedExtensions(arg1) {
  return window['go']['commands']['AppCommands']['SetSupportedExtensions'](arg1);
}

export function SetTaggerThresholdOverridesJSON(arg1) {
  return window['go']['commands']['AppCommands']['SetTaggerThresholdOverridesJSON'](arg1);
}

export function ShutdownBackground(arg1) {
  return window['go']['commands']['AppCommands']['ShutdownBackground'](arg1);
}

export function StartAIRestore() {
  return window['go']['commands']['AppCommands']['StartAIRestore']();
}

export function SyncLibraryViewer(arg1) {
  return window['go']['commands']['AppCommands']['SyncLibraryViewer'](arg1);
}

export function TaggerAnalysisHandler(arg1, arg2) {
  return window['go']['commands']['AppCommands']['TaggerAnalysisHandler'](arg1, arg2);
}

export function ToggleAssetFavorite(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ToggleAssetFavorite'](arg1, arg2);
}

export function UpdateAssetColorLabel(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetColorLabel'](arg1, arg2);
}

export function UpdateAssetNote(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetNote'](arg1, arg2);
}

export function UpdateAssetRating(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetRating'](arg1, arg2);
}

export function UpdateAssetStatus(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetStatus'](arg1, arg2);
}

export function UpdateLibrary(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['UpdateLibrary'](arg1, arg2, arg3);
}

export function UpdateModelProfile(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateModelProfile'](arg1, arg2);
}

export function UpdatePost(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['commands']['AppCommands']['UpdatePost'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePromptProject(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdatePromptProject'](arg1, arg2);
}

export function VerifyAIModel(arg1, arg2) {
  return window['go']['commands']['AppCommands']['VerifyAIModel'](arg1, arg2);
}
