// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary(arg1, arg2) {
  return window['go']['commands']['AppCommands']['AddLibrary'](arg1, arg2);
}

export function AttachAssetsToPost(arg1, arg2) {
  return window['go']['commands']['AppCommands']['AttachAssetsToPost'](arg1, arg2);
}

export function BulkDeleteAssets(arg1) {
  return window['go']['commands']['AppCommands']['BulkDeleteAssets'](arg1);
}

export function BulkUpdateColorLabel(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateColorLabel'](arg1, arg2);
}

export function BulkUpdateFavorite(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateFavorite'](arg1, arg2);
}

export function BulkUpdateRating(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateRating'](arg1, arg2);
}

export function BulkUpdateStatus(arg1, arg2) {
  return window['go']['commands']['AppCommands']['BulkUpdateStatus'](arg1, arg2);
}

export function CancelScan() {
  return window['go']['commands']['AppCommands']['CancelScan']();
}

export function CopyAssets(arg1) {
  return window['go']['commands']['AppCommands']['CopyAssets'](arg1);
}

export function CreatePostAccount(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['CreatePostAccount'](arg1, arg2, arg3);
}

export function CreatePostDraft(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['CreatePostDraft'](arg1, arg2, arg3);
}

export function CreatePostTarget(arg1, arg2) {
  return window['go']['commands']['AppCommands']['CreatePostTarget'](arg1, arg2);
}

export function CreateTag(arg1, arg2) {
  return window['go']['commands']['AppCommands']['CreateTag'](arg1, arg2);
}

export function DeletePost(arg1) {
  return window['go']['commands']['AppCommands']['DeletePost'](arg1);
}

export function DeletePostAccount(arg1) {
  return window['go']['commands']['AppCommands']['DeletePostAccount'](arg1);
}

export function DeletePostTarget(arg1) {
  return window['go']['commands']['AppCommands']['DeletePostTarget'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['commands']['AppCommands']['DeleteTag'](arg1);
}

export function DisableLibrary(arg1) {
  return window['go']['commands']['AppCommands']['DisableLibrary'](arg1);
}

export function EnableLibrary(arg1) {
  return window['go']['commands']['AppCommands']['EnableLibrary'](arg1);
}

export function GetAppBootstrap() {
  return window['go']['commands']['AppCommands']['GetAppBootstrap']();
}

export function GetAssetDetail(arg1) {
  return window['go']['commands']['AppCommands']['GetAssetDetail'](arg1);
}

export function GetExcludedDirs(arg1) {
  return window['go']['commands']['AppCommands']['GetExcludedDirs'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['commands']['AppCommands']['GetFolderTree'](arg1);
}

export function GetPostsByAsset(arg1) {
  return window['go']['commands']['AppCommands']['GetPostsByAsset'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['commands']['AppCommands']['GetSetting'](arg1);
}

export function GetSupportedExtensions() {
  return window['go']['commands']['AppCommands']['GetSupportedExtensions']();
}

export function ListAssets(arg1) {
  return window['go']['commands']['AppCommands']['ListAssets'](arg1);
}

export function ListLibraries() {
  return window['go']['commands']['AppCommands']['ListLibraries']();
}

export function ListPostAccounts() {
  return window['go']['commands']['AppCommands']['ListPostAccounts']();
}

export function ListPostTargets() {
  return window['go']['commands']['AppCommands']['ListPostTargets']();
}

export function ListPosts(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ListPosts'](arg1, arg2);
}

export function ListTags() {
  return window['go']['commands']['AppCommands']['ListTags']();
}

export function MoveAssets(arg1) {
  return window['go']['commands']['AppCommands']['MoveAssets'](arg1);
}

export function RemoveLibrary(arg1) {
  return window['go']['commands']['AppCommands']['RemoveLibrary'](arg1);
}

export function ScanFolder(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['ScanFolder'](arg1, arg2, arg3);
}

export function ScanLibrary(arg1) {
  return window['go']['commands']['AppCommands']['ScanLibrary'](arg1);
}

export function SelectFolder() {
  return window['go']['commands']['AppCommands']['SelectFolder']();
}

export function SetAssetTags(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SetAssetTags'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['commands']['AppCommands']['SetContext'](arg1);
}

export function SetExcludedDirs(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SetExcludedDirs'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['commands']['AppCommands']['SetSetting'](arg1, arg2);
}

export function SetSupportedExtensions(arg1) {
  return window['go']['commands']['AppCommands']['SetSupportedExtensions'](arg1);
}

export function ToggleAssetFavorite(arg1, arg2) {
  return window['go']['commands']['AppCommands']['ToggleAssetFavorite'](arg1, arg2);
}

export function UpdateAssetColorLabel(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetColorLabel'](arg1, arg2);
}

export function UpdateAssetNote(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetNote'](arg1, arg2);
}

export function UpdateAssetRating(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetRating'](arg1, arg2);
}

export function UpdateAssetStatus(arg1, arg2) {
  return window['go']['commands']['AppCommands']['UpdateAssetStatus'](arg1, arg2);
}

export function UpdateLibrary(arg1, arg2, arg3) {
  return window['go']['commands']['AppCommands']['UpdateLibrary'](arg1, arg2, arg3);
}

export function UpdatePost(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['commands']['AppCommands']['UpdatePost'](arg1, arg2, arg3, arg4, arg5);
}
