// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {scanner} from '../models';
import {context} from '../models';

export function AddLibrary(arg1:string,arg2:string):Promise<commands.LibraryDTO>;

export function AttachAssetsToPost(arg1:number,arg2:Array<number>):Promise<void>;

export function BulkDeleteAssets(arg1:Array<number>):Promise<void>;

export function BulkUpdateColorLabel(arg1:Array<number>,arg2:string):Promise<void>;

export function BulkUpdateFavorite(arg1:Array<number>,arg2:boolean):Promise<void>;

export function BulkUpdateRating(arg1:Array<number>,arg2:number):Promise<void>;

export function BulkUpdateStatus(arg1:Array<number>,arg2:string):Promise<void>;

export function CancelScan():Promise<void>;

export function CopyAssets(arg1:commands.CopyRequest):Promise<commands.CopyResult>;

export function CreatePostAccount(arg1:number,arg2:string,arg3:string):Promise<commands.PostAccountDTO>;

export function CreatePostDraft(arg1:string,arg2:string,arg3:string):Promise<commands.PostDTO>;

export function CreatePostTarget(arg1:string,arg2:string):Promise<commands.PostTargetDTO>;

export function CreateTag(arg1:string,arg2:string):Promise<commands.TagDTO>;

export function DeletePost(arg1:number):Promise<void>;

export function DeletePostAccount(arg1:number):Promise<void>;

export function DeletePostTarget(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DisableLibrary(arg1:number):Promise<void>;

export function EnableLibrary(arg1:number):Promise<void>;

export function GetAppBootstrap():Promise<{[key: string]: any}>;

export function GetAssetDetail(arg1:number):Promise<commands.AssetDTO>;

export function GetExcludedDirs(arg1:number):Promise<Array<string>>;

export function GetFolderTree(arg1:number):Promise<Array<commands.FolderDTO>>;

export function GetPostsByAsset(arg1:number):Promise<Array<commands.PostDTO>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSupportedExtensions():Promise<Array<string>>;

export function ListAssets(arg1:commands.AssetListRequest):Promise<commands.AssetListResponse>;

export function ListLibraries():Promise<Array<commands.LibraryDTO>>;

export function ListPostAccounts():Promise<Array<commands.PostAccountDTO>>;

export function ListPostTargets():Promise<Array<commands.PostTargetDTO>>;

export function ListPosts(arg1:number,arg2:number):Promise<Array<commands.PostDTO>>;

export function ListTags():Promise<Array<commands.TagDTO>>;

export function MoveAssets(arg1:commands.MoveRequest):Promise<commands.MoveResult>;

export function RemoveLibrary(arg1:number):Promise<void>;

export function ScanFolder(arg1:string,arg2:number,arg3:number):Promise<scanner.FolderScanResult>;

export function ScanLibrary(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetAssetTags(arg1:number,arg2:Array<number>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetExcludedDirs(arg1:number,arg2:Array<string>):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetSupportedExtensions(arg1:Array<string>):Promise<void>;

export function ToggleAssetFavorite(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAssetColorLabel(arg1:number,arg2:string):Promise<void>;

export function UpdateAssetNote(arg1:number,arg2:string):Promise<void>;

export function UpdateAssetRating(arg1:number,arg2:number):Promise<void>;

export function UpdateAssetStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateLibrary(arg1:number,arg2:string,arg3:string):Promise<commands.LibraryDTO>;

export function UpdatePost(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<commands.PostDTO>;
