<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <StripSymbols>true</StripSymbols>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Lumine.App.Smoke</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Lumine.Core/Lumine.Core.csproj" />
    <ProjectReference Include="../Lumine.Diagnostics/Lumine.Diagnostics.csproj" />
    <ProjectReference Include="../Lumine.Library/Lumine.Library.csproj" />
    <ProjectReference Include="../Lumine.Image/Lumine.Image.csproj" />
    <ProjectReference Include="../Lumine.Viewer/Lumine.Viewer.csproj" />
  </ItemGroup>
</Project>
